
(defgroup nphtml nil
  "convension for writing html or svg")
(defcustom nphtml-lang-attr "en"
	"lang attribute for html tag")
(defconst nphtml--builtin-html-args
  '((:alias dateComment :para (concat "FirstEdit: " (current-time-string)) :type comment)
    (:alias comment     :para ""                                           :type comment)
    (:tag a  :type inline :attrs (href ""))
		(:tag p  :type inline)
    (:tag h1 :type inline)
    (:tag h2 :type inline)
    (:tag h3 :type inline)
    (:tag h4 :type inline)
    (:tag h5 :type inline)
    (:tag h6 :type inline)
    (:tag !DOCTYPE :hidden t :type void :spec html)
    (:tag html :type blocky :attrs (lang ,nphtml-lang-attr)
	  :prepend (dateComment !DOCTYPE)
	  :nest (head body))
    (:tag body :type blocky :nest (header main footer) :hidden t)
    (:tag head :type blocky :nest (title chmeta) :hidden t)
    (:tag meta :alias chmeta :type void :attrs (charset utf-8) :hidden t)
    (:tag meta :type void)
    (:tag title :type inline)
    (:tag i)
    (:tag ins)
    (:tag isindex)
    (:tag kbd)
    (:tag label)
    (:tag lang)
    (:tag legend)
    (:tag li :type inline)
    (:tag main :type blocky)
    (:tag map)
    (:tag mark)
    (:tag math)
    
    (:tag meter)
    (:tag nav  :type blocky)
		(:tag ol   :type blocky)
		(:tag ul   :type blocky)
		(:tag img  :type void :attrs (src "" alt ""))
    (:tag nobr)
    (:tag noframes)
    (:tag noscript)
    (:tag object)
    (:tag optgroup)
    (:tag option)
    (:tag output)
    (:tag over)
    (:tag param)
    (:tag person)
    (:tag pre)
    (:tag progress)
    (:tag q)
    (:tag rev)
    (:tag rp)
    (:tag rt)
    (:tag ruby)
    (:tag s)
    (:tag samp)
    (:tag script)
    (:tag section)
    (:tag small)
    (:tag source)
    (:tag span :type inline)
    (:tag strong :type inline)
    (:tag style)
    (:tag sub :type inline)
    (:tag summary)
    (:tag sup :type inline)
    (:tag time)
    
    (:tag tr)
    (:tag track)
    (:tag tt)
    (:tag u)
    (:tag var)
    (:tag video)
    (:tag wbr :type void)
    ))


(defvar nphtml--str-arg-hash nil)
(defvar nphtml--hiddens nil)
(defvar nphtml--completion-list nil)
(defun nphtml--push-hash-internal (nphtml-arg)
  (let ((alias (nphtml--args-get-kind :alias nphtml-arg)))
    (puthash alias nphtml-arg nphtml--str-arg-hash)
    (if (nphtml--args-get-kind :hidden nphtml-arg)
	(cl-pushnew alias nphtml--hiddens :test #'string-equal)
      (cl-pushnew alias nphtml--completion-list :test #'string-equal))))
(defun nphtml--push-hash (nphtml-args)
  (dolist (nphtml-arg nphtml-args)
    (nphtml--push-hash-internal nphtml-arg)))
(defun nphtml--init-hash nil
  (setf nphtml--str-arg-hash (make-hash-table :test 'equal))
  (nphtml--push-hash nphtml--builtin-html-args)
  (when nphtml-add-gblogger
    (nphtml--push-hash nphtml--builtin-gblogger-args)))
(defun nphtml-reinit-hash nil
	(interactive)
	(setf nphtml--str-arg-hash nil
				nphtml--completion-list nil)
	(nphtml--init-hash))
(defcustom nphtml-immediate-error nil
  "determines behaviour when you try to gethash with unregisted key"
  :type 'boolean)
(defun nphtml--get-hash (alias)
  (when (null alias) (error "had tryied to gethash with nil key"))
  (when (null nphtml--str-arg-hash) (nphtml--init-hash));just init when hash is not inited
  (let* ((astr   (if (symbolp alias) (symbol-name alias) alias))
	 (default (list :tag astr))
	 (hashv (gethash astr nphtml--str-arg-hash nil)))
    (if hashv hashv;hashv exists immediately returns it
      (if nphtml-immediate-error (error "you tried to get unhashed key val %s" alias)
	default))))

(defun nphtml--get-hash-weakly (alias)
  (let ((gotten (nphtml--get-hash alias)))
    (plist-put gotten :prepend nil)
    (plist-put gotten :nest nil)
    (plist-put gotten :append nil)
    gotten))
;; (nphtml--get-hash 'html)

(provide 'nphtml-args-builtin)
